### ISSUE TITLE
Running signet

### ISSUE THREAD

**Issue by openoms** [GaloyMoney/charts#1123]
Will run signet locally and discuss moving staging from testnet.

Advantages:
- reliable blocktimes
- no block-storms
- small blockchain (IBD ~ 10 mins on a laptop)
- Electrum works 
- Faucets are available (see below)

Disadvantages:
- no lndmon support yet https://github.com/lightninglabs/lndmon/issues/80
- no Loop support yet https://github.com/lightninglabs/loop/issues/522
- fewer nodes on the network
- staging would need an accounting reset when converting (might be an advantage)
- no known 3rd party services / test shops available
- pending in:
  - https://github.com/alexbosworth/ln-sync/issues/5
  - https://github.com/bitcoinjs/bitcoinjs-lib/issues/1820

Electrum servers:
* signet-electrumx.wakiyamap.dev:50002:s
* electrum.emzy.de:53002:s
* node202.fra.mempool.space:60602

Block explorer: 
* https://mempool.space/signet
* https://explorer.bc-2.jp/

Faucets:
- https://signet.bc-2.jp/
- https://signetfaucet.bublina.eu.org/
- https://faucet.sirion.io/ (LN only)

LN explorer: 
- https://mempool.space/signet/lightning
- https://signet-lightning.wakiyamap.dev/

Places to send signet sats to:
* BTCPay PoS (BIP21 payment link by default - click to `lightning` for BOLT11 only) https://signet.demo.btcpayserver.org/apps/2SCdQhwFm464BcHxXn44kRVg3iCr/pos
* LNbits wallet (receive only for now): https://signet.diynodes.com/wallet?usr=7a9d00aa89f44af1b1808244d8caafef&wal=ce0e6e5827224618aa75a56ac73f2ef2
(https://github.com/lnbits/lnbits/issues/1111)
* https://sigpay.sirion.io/apps/33Au5UDsPWnUL5GVT8q1Yjovw83K/crowdfund

Plebnet playground using a separate signet: https://www.plebnet.fun/

More info: https://en.bitcoin.it/wiki/Signet

Best wallet to use with signet on Android:
https://github.com/nbd-wtf/obw/releases/

scan this with OBW-signet to receive a hosted channel on signet (should also provide some local balance ):
![image](https://user-images.githubusercontent.com/43343391/206720745-838fb788-d09d-4af9-8400-32c2137dd30b.png)

Galoy staging LND1: https://mempool.space/signet/lightning/node/024e679c1a77143029b806f396f935fa6cd0744970f412667adfc75edbbab54d7a

Scan the URI to open a channel:
![image](https://user-images.githubusercontent.com/43343391/200599602-093133de-4d40-4ab3-9ed6-4f4af1d4527c.png)

[Sparrow](https://sparrowwallet.com/download/) works with signet and Taproot accounts as well. To use with signet open menu - Tools - Restart  in Testnet and set a Private Electrum server serving signet like: `node202.fra.mempool.space` port: `60602` with SSL.`

[Electrum](https://electrum.org/#download) - couldn't send or receive lightning payments on signet with electrum yet.
* start with `electrum-4.4.0-x86_64.AppImage --signet`
* `menu` - `Wallet` - `Information` and restart to activate lightning
![image](https://user-images.githubusercontent.com/43343391/174888608-268477a1-4f9b-4eab-be16-937c7361ad75.png)

**Comment by openoms** [comment]
Blocked by an old npm / yarn package: https://github.com/GaloyMoney/galoy/issues/1387

**Comment by henrysmit420** [comment]
Mine bitcoin for free here https://www.btcs.love/invite/4nc58

**Comment by openoms** [comment]
https://github.com/GaloyMoney/charts/pull/1125 is working now locally

**Comment by openoms** [comment]
New (and far the best) signet LN eplorer:
https://mempool.space/signet/lightning

Only 23 nodes are currently on the default signet network, but has a good mix of LND, CLN and Eclair already

**Comment by openoms** [comment]
Loop doesn't support signet yet either:
```
$ k -n galoy-sig-bitcoin   logs   lnd1-loop-0 
Defaulted container "loop" out of: loop, export-secrets
loopd exited with an error: Invalid value `signet' for option `--network'. Allowed values are: regtest, testnet, mainnet or simnet
Invalid value `signet' for option `--network'. Allowed values are: regtest, testnet, mainnet or simnet
```

lndmon:
```
$ k -n galoy-sig-bitcoin   logs   lnd1-lndmon-7f84d8595-whz8x
Invalid value `signet' for option `--lnd.network'. Allowed values are: regtest, testnet, mainnet or simnet
Invalid value `signet' for option `--lnd.network'. Allowed values are: regtest, testnet, mainnet or simnet
```

**Comment by nicolasburtey** [comment]
the first part of this issue should probably be a SIGNET.MD (or something like that) file in the repo?

**Comment by openoms** [comment]
> the first part of this issue should probably be a SIGNET.MD (or something like that) file in the repo?

Good point, will prepare a PR!
