### ISSUE TITLE
jwt-secret should be kept when the associated helm charts is being delete

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/charts#114]
currently the jwt-secret is not being kept when the charts is deleted. but this is something that should stay so that if the chart is unintentionally removed, we could still restore it, and users who are logged in are not automatically logged out.

**Comment by nicolasburtey** [comment]
ticket still relevant @krtk6160 ?

**Comment by krtk6160** [comment]
We added a

**Comment by krtk6160** [comment]
@nicolasburtey #1059 Will fix it
