### ISSUE TITLE
Add PeerSwap

### ISSUE THREAD

**Issue by openoms** [GaloyMoney/charts#1208]
Building on testing with: https://github.com/rootzoll/raspiblitz/pull/3202

In case of a congested mempool could consider running Liquid swaps as well (needs an Elements node in the pod with PeerSwap), but holding it off as it would significantly increase the complexity of accounting in the Galoy instance.

**Comment by nicolasburtey** [comment]
PeerSwap can work with bitcoin layer 1?

**Comment by openoms** [comment]
Yes, it uses the onchain wallets of LND or CLN by default. Liquid is only an extra option.

**Comment by anthr76** [comment]
It has worked well for me here https://github.com/anthr76/infra/blob/main/k8s/base/crypto/peerswap/helm-release.yaml

**Comment by openoms** [comment]
Closing this as there were no updates on PeerSwap in 2023.
