### ISSUE TITLE
{{- range $.Values.deployment }} not a best practice for helm 

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/charts#186]
it makes it hard to understand what is deployed. I had made it initially to avoid repeating all the environment variables across the charts. but this could be avoided by using some helm library / `include` function that acts as template

**Comment by bodymindarts** [comment]
I think the approach taken in the oppentelemetry chart for structural sharing is okay https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/templates/_pod.tpl. 

But best is probably no sharing.

**Comment by nicolasburtey** [comment]
fixed by @sandipndev
