### ISSUE TITLE
plot the different bitcoind wallet in grafana

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/charts#27]

**Comment by krtk6160** [comment]
@nicolasburtey Do we need any other graph for bitcoind (apart from what was added yesterday)?

**Comment by nicolasburtey** [comment]
this would be useful to have more info about the wallet. the current Bitcoin dashboard is mostly related to network/difficulty/fee estimation. 

I'm not sure if there is an exporter handy for that. I would consider this low priority for now. we're unlikely to have dust UTXOs issue / consolidation needs unlike for the hot wallet.

**Comment by krtk6160** [comment]
Don't think this is relevant anymore
