### ISSUE TITLE
perfhistograms

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/charts#627]
add `prometheus.perfhistograms=true` (https://github.com/lightningnetwork/lnd/blob/master/sample-lnd.conf#L428) (and update lndmon chart?)

**Comment by krtk6160** [comment]
@nicolasburtey Is this still relevant? [Here's](https://github.com/lightningnetwork/lnd/blob/master/sample-lnd.conf#L442) the docs about the flag.

**Comment by nicolasburtey** [comment]
I dont really remember the context. closing it down.

one useful topic for prometheus is actually to prune the charts and remove all the one that honeycomb is fullfilling.
