### ISSUE TITLE
improve high availability -> set pod rules to run on different nodes for lnd/redis/mongodb

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/charts#763]
redis and mongodb run on 3 pods with redundancy. so that if one pod goes down the app continue working
with the PR https://github.com/GaloyMoney/galoy/pull/199, several instance of lnd will run in parrellel, with a failover mechanism.

to really favor high availability, those pods should not run on the same node. 

it should be investigate whether we can have generic rules that apply on any kubernetes cluster (generic rules), or whether it's really instance dependent (less ideal)

**Comment by krtk6160** [comment]
Looks like [mongodb](https://github.com/bitnami/charts/blob/main/bitnami/mongodb/values.yaml#LL455C28-L455C28) and [redis](https://github.com/bitnami/charts/blob/main/bitnami/redis/values.yaml#L323) helm charts now set a "soft" pod anti-affinity setting by default. I think we can close this issue.
